# CARINA (Controlled Artificial Road-traffic Intelligence Network Architecture) is an open-source AI ecosystem for real-time, adaptive control of urban traffic light networks.
# Copyright (C) 2026 Gabriel Moraes - Noxfort Systems
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# File: src/slm/output_sanitizer.py
# Author: Gabriel Moraes
# Date: July 29, 2026

import re

class SLMOutputSanitizer:
    """
    Sanitizes raw output strings generated by LLMs:
    Removes thinking blocks (<think>...</think>), emojis, backticks, and stray formatting.
    """

    @staticmethod
    def sanitize(raw_text: str) -> str:
        """Cleans think blocks, graphic emojis, stray backticks, and extra whitespace."""
        if not raw_text:
            return ""

        # Clean thinking blocks, including enclosing markdown blocks if present
        report_text = re.sub(r"```[a-zA-Z]*\s*<think>.*?</think>\s*```", "", raw_text, flags=re.DOTALL)
        report_text = re.sub(r"<think>.*?</think>", "", report_text, flags=re.DOTALL)
        report_text = re.sub(r"<think>.*", "", report_text, flags=re.DOTALL).strip()
        report_text = report_text.replace("</think>", "")
        report_text = re.sub(r"^\s*`+\s*", "", report_text)

        # Strict post-processing removal of any emojis or graphic symbols
        emoji_pattern = re.compile(r"[\U00010000-\U0010ffff\u2600-\u27ff\u2300-\u23ff\u2b50\u2b55\u200d\ufe0f]", flags=re.UNICODE)
        report_text = emoji_pattern.sub("", report_text)

        return report_text.strip()
