# CARINA (Controlled Artificial Road-traffic Intelligence Network Architecture) is an open-source AI ecosystem for real-time, adaptive control of urban traffic light networks.
# Copyright (C) 2026 Gabriel Moraes - Noxfort Systems
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# File: src/utils/logging_setup.py
# Author: Gabriel Moraes
# Date: September 17, 2025

"""
Configures a logging system that writes to the console and to a file
in real-time, with support for universal characters (UTF-8) and different log levels
for each output.
"""
import logging
from logging.handlers import RotatingFileHandler
import sys
import os
import gzip
import warnings

# Suppress PyTorch weight_norm deprecation warning
warnings.filterwarnings("ignore", category=FutureWarning, message=".*weight_norm.*")
warnings.filterwarnings("ignore", category=FutureWarning, module="torch.nn.utils.weight_norm")

def gzip_namer(name: str) -> str:
    return name + ".gz"

def gzip_rotator(source: str, dest: str) -> None:
    with open(source, 'rb') as sf:
        with gzip.open(dest, 'wb') as df:
            df.writelines(sf)
    os.remove(source)

def setup_logging(log_dir: str):
    """
    Configures logging for the console and log file using UTF-8.
    The log file captures everything (DEBUG), while the console is cleaner (INFO).
    """
    log_file_path = os.path.join(log_dir, 'console_output.log')
    
    log_formatter = logging.Formatter('%(asctime)s [%(levelname)s] - %(message)s')
    
    root_logger = logging.getLogger()
    # --- FIX (Part 1): Sets the lowest level in the main logger ---
    # This allows it to pass all messages to the handlers, which will do the filtering.
    root_logger.setLevel(logging.DEBUG)
    
    # Cleans up existing handlers to avoid log duplication
    if root_logger.hasHandlers():
        root_logger.handlers.clear()

    class FletAsyncShutdownFilter(logging.Filter):
        """Filters harmless error messages generated by asyncio during Flet UI shutdown."""
        def filter(self, record):
            if record.exc_info:
                _, exc_value, _ = record.exc_info
                if exc_value and "cannot schedule new futures" in str(exc_value):
                    return False
            if isinstance(record.msg, str) and "cannot schedule new futures" in record.msg:
                return False
            return True

    # --- FIX (Part 2): Configure FileHandler to record EVERYTHING ---
    # 1. Handler to save the logs to a file, specifying UTF-8 encoding
    file_handler = RotatingFileHandler(log_file_path, maxBytes=10 * 1024 * 1024, backupCount=100, encoding='utf-8')
    file_handler.namer = gzip_namer
    file_handler.rotator = gzip_rotator
    file_handler.setFormatter(log_formatter)
    file_handler.setLevel(logging.DEBUG) # Writes everything from DEBUG to CRITICAL to the file.
    file_handler.addFilter(FletAsyncShutdownFilter())
    root_logger.addHandler(file_handler)

    # --- FIX (Part 3): Configure ConsoleHandler to be less verbose ---
    # 2. Handler to show logs in console
    console_handler = logging.StreamHandler(sys.stdout)
    console_handler.setFormatter(log_formatter)
    console_handler.setLevel(logging.INFO) # Shows only from INFO to CRITICAL on the console.
    console_handler.addFilter(FletAsyncShutdownFilter())
    root_logger.addHandler(console_handler)

    def handle_exception(exc_type, exc_value, exc_traceback):
        if issubclass(exc_type, KeyboardInterrupt):
            sys.__excepthook__(exc_type, exc_value, exc_traceback)
            return
        # The exception will be caught by both handlers
        root_logger.critical("Exceção não tratada:", exc_info=(exc_type, exc_value, exc_traceback))

    sys.excepthook = handle_exception
    
    # This message will only appear in the console, as it is INFO.
    logging.info("Sistema de Logging (Modo Tempo Real, UTF-8) configurado.")
    # This message will only appear in the .txt file, as it is DEBUG.
    logging.debug("Logger configurado. FileHandler=DEBUG, StreamHandler=INFO.")
    
    # --- SILENCE VERBOSE THIRD-PARTY MODULES ---
    logging.getLogger("websockets").setLevel(logging.WARNING)
    logging.getLogger("websockets.server").setLevel(logging.WARNING)
    logging.getLogger("websockets.client").setLevel(logging.WARNING)